### ISSUE TITLE
LAB17

### ISSUE THREAD

**Issue by UsingCoding** [Wafell/web-development#5]
### 17.1

- [x] Ваша  процедура делает слишком много: она читает цифру и тут же складывает с суммой, а потом выводит. Стоит вынести и сделать так, чтобы ReadDigit только считывал цифру

**Comment by Wafell** [comment]
Готово

**Comment by sokolnikovalexey** [comment]
1. Переменная I не инициализирована
2. Непонятен смысл конструкции
```
 IF EOLN
  THEN
    WRITELN
  ELSE
    BEGIN
      IF (NOT EOLN) 
```
